FROM rust:1.86-alpine AS builder

RUN apk add --no-cache \
    musl-dev \
    openssl-dev \
    pkgconfig \
    gcc

WORKDIR /app


COPY Cargo.toml ./

COPY src ./src

RUN cargo build --release

FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache \
    openssl \
    ca-certificates

COPY --from=builder /app/target/release/counter /usr/local/bin/counter
COPY settings ./settings

CMD ["counter"]