FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build && npm prune --omit=dev && npm cache clean --force

FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app /app

EXPOSE 8000

CMD ["npm", "run", "start"]