employee:
  getByCredentials:
    SELECT
      employee_cid AS ci,
      employee_email AS email,
      employee_name AS name,
      employee_passwd AS passwd,
      phone_num
    FROM
      employee
    WHERE
      employee_cid = $1

counter:
  testQuery: |
    SELECT 1 AS value

  client:
    exists: |
      SELECT EXISTS(SELECT 1 FROM client WHERE client_cid = $1)

  package:
    getReceived: |
      SELECT 
        p.package_id AS id,
        p.package_desc AS desc,
        p.package_weight AS weight,
        p.package_width AS width,
        p.package_length AS length,
        p.package_height AS height,
        s.guide_num,
        s.shipment_dt,
        s.destination_address
      FROM 
        shipment s
      JOIN 
        package p ON s.package_id = p.package_id
      WHERE 
        s.receiver_cid = $1 
        AND s.status_id = 2

  shipment:
    getStatus: |
      SELECT 
        status_id
      FROM 
        shipment 
      WHERE 
        guide_num = $1
    
    updateToPickedUp: |
      UPDATE shipment
      SET status_id = 3
      WHERE guide_num = $1

    create: |
      WITH new_pkg AS (
        INSERT INTO package (package_desc, package_weight, package_width, package_length, package_height)
        VALUES ($1, $2, $3, $4, $5)
        RETURNING package_id
      )
      INSERT INTO shipment (
        package_id,
        sender_cid,
        receiver_cid,
        destination_address,
        status_id,
        guide_num,
        shipment_dt
      )
      VALUES (
        (SELECT package_id FROM new_pkg),
        $6,
        $7,
        $8,
        0,
        $9,
        CURRENT_TIMESTAMP
      )
      RETURNING shipment_id, guide_num

    getTrackingByGuideNum: |
      SELECT
        s.guide_num,
        s.status_id,
        ss.status_desc,
        s.destination_address,
        s.shipment_dt,
        p.package_desc
      FROM
        shipment s
      JOIN
        status_shipment ss ON ss.status_id = s.status_id
      JOIN
        package p ON p.package_id = s.package_id
      WHERE
        s.guide_num = $1